controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

stm32f4_hardware:
  ros__parameters:
    joints:
      - left_wheel
      - right_wheel
    wheel_separation: 0.5  # meters, adjust to your robot
    wheel_radius: 0.1     # meters, adjust to your robot
    encoder_resolution: 4000  # ticks per revolution, adjust to your encoders

diff_drive_controller:
  ros__parameters:
    left_wheel: "left_wheel"
    right_wheel: "right_wheel"
    wheel_separation: 0.5
    wheel_radius: 0.1
    publish_rate: 50.0
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
